name: "Deploy Application"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql
          ini-values: memory_limit=-1
          tools: composer

      # 3. Instalar dependencias de Composer
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      # 4. Crear archivo .env para producción
      - name: Create .env file
        run: cp .env.example .env

      # 5. Configurar variables de entorno desde GitHub Secrets
      - name: Update environment variables
        run: |
          sed -i "s|DB_CONNECTION=mysql|DB_CONNECTION=${{ secrets.DB_CONNECTION }}|g" .env
          sed -i "s|DB_HOST=127.0.0.1|DB_HOST=${{ secrets.DB_HOST }}|g" .env
          sed -i "s|DB_PORT=3306|DB_PORT=${{ secrets.DB_PORT }}|g" .env
          sed -i "s|DB_DATABASE=laravel|DB_DATABASE=${{ secrets.DB_DATABASE }}|g" .env
          sed -i "s|DB_USERNAME=root|DB_USERNAME=${{ secrets.DB_USERNAME }}|g" .env
          sed -i "s|DB_PASSWORD=|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|g" .env

      # 6. Ejecutar migraciones
      - name: Run migrations
        run: php artisan migrate --force

      # 7. Limpiar y optimizar la aplicación
      - name: Clear and optimize application
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # 8. Configurar permisos (opcional, dependiendo del servidor)
      - name: Set file permissions
        run: |
          chmod -R 775 storage bootstrap/cache
          chown -R www-data:www-data .

      # 9. Despliegue completado
      - name: Notify deployment completion
        run: echo "Deployment to production completed successfully!"
